### ISSUE TITLE
Can you run it success?

### ISSUE THREAD

**Issue by happyhq** [waqarrashid33/cuckoo-droid#1]
I used this code too.But I can't  do it  success .Have you do it  success with analyst a APK?

**Comment by waqarrashid33** [comment]
Its just a fork now, it doesn't work out of the box. I will make some changes in it after which it will work out of the box.

**Comment by happyhq** [comment]
Its can  work now。 I  use   vmware   as   box   and   run host  on  macOS。It  success！Thank you!
